### PR TITLE
implemented method for time vector

### PR DESCRIPTION
**Pull request by AlexSpacek**
Implemented a method for generating the temporal vector in physics.py

What do you think about this? Does it make sense to have it as a seperate method and call it whenever you need the time vector?

### CODE REVIEW

**Comment by fracapuano** [comment]
Hi Alex, 
Love the idea of making a function to do this! Would you mind extending this usage to all the other elements in LaserModel which might benefit from this function usage? 

Commit once you have done it please. 
Cheers, 
Francesco

PS: I'll be taking a couple of days off starting from now. I might pop up here and there but as a general indication see you on Tuesday

**Comment by AlexSpacek** [comment]
Ok, will do.
Enjou your day off!

**Comment by AlexSpacek** [comment]
I hope I found all the instances that require the time vector...

**Comment by fracapuano** [comment]
Hey Alex. Looks like you did. I'm merging in the branch. 

PS: I'm back at ELI, if you need anything don't hesitate stop by the office/write to me

**Pull request merged**
